name = "telegram-bot"
main = "src/main.py"
compatibility_date = "2024-03-20"
compatibility_flags = [
  "python_workers",
  "python_stdlib", 
  "nodejs_compat"
]

[build]
command = "cp -r src ."
upload_dir = "src"
