name = "tetegram-potmg"
main = "src/main.py"
compatibility_date = "2024-03-20"
compatibility_flags = ["python_stdlib", "nodejs_compat"]

[build]
command = "pip install -r requirements.txt && cp -r ../src ."
upload_dir = "src"
